<Project>
  <PropertyGroup>
    <VersionPrefix>1.1.0</VersionPrefix>
    <Authors>Kelson Martins</Authors>
    <Company>KelsonMartins</Company>
    <Copyright>Copyright © Kelson Martins 2026</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/KelsonMartins/effective-guacamole</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

</Project>
